//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutcoldSolutions.Web.Blog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutcoldSolutions.Web.Blog.Resources.ResourceEn", typeof(ResourceEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me / CV.
        /// </summary>
        internal static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Comment.
        /// </summary>
        internal static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body* (you can use html tags).
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phone.
        /// </summary>
        internal static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment sucessefully posted..
        /// </summary>
        internal static string CommentAdded {
            get {
                return ResourceManager.GetString("CommentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment sucessefully posted but marked as spam..
        /// </summary>
        internal static string CommentAddedAsSpam {
            get {
                return ResourceManager.GetString("CommentAddedAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment didn&apos;t added. Please check that you didn&apos;t use java scripts in comment text. If you think that error happend please give me know..
        /// </summary>
        internal static string CommentNotAdded {
            get {
                return ResourceManager.GetString("CommentNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content on this site represents my own personal opinions and thoughts at the time of posting..
        /// </summary>
        internal static string ContentOfSite {
            get {
                return ResourceManager.GetString("ContentOfSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add comment..
        /// </summary>
        internal static string CouldntAddComment {
            get {
                return ResourceManager.GetString("CouldntAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t execute this action.
        /// </summary>
        internal static string CouldntExecute {
            get {
                return ResourceManager.GetString("CouldntExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t show preview..
        /// </summary>
        internal static string CouldntShowPreview {
            get {
                return ResourceManager.GetString("CouldntShowPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have the same comment in our database. Looks like you are trying to add your comment at second time. Please refresh this page after couple minutes and you will find your comment (if it not marked as spam)..
        /// </summary>
        internal static string DublicateComment {
            get {
                return ResourceManager.GetString("DublicateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email  (will not be published).
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the body of comment.
        /// </summary>
        internal static string FillBodyComment {
            get {
                return ResourceManager.GetString("FillBodyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill email or uncheck email notification.
        /// </summary>
        internal static string FillEmailComment {
            get {
                return ResourceManager.GetString("FillEmailComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to find more, go to the {0} page....
        /// </summary>
        internal static string FindMore {
            get {
                return ResourceManager.GetString("FindMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment text.
        /// </summary>
        internal static string InputComment {
            get {
                return ResourceManager.GetString("InputComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your email.
        /// </summary>
        internal static string InputEmail {
            get {
                return ResourceManager.GetString("InputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your name.
        /// </summary>
        internal static string InputName {
            get {
                return ResourceManager.GetString("InputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your web.
        /// </summary>
        internal static string InputWeb {
            get {
                return ResourceManager.GetString("InputWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a comment.
        /// </summary>
        internal static string LeaveAcomment {
            get {
                return ResourceManager.GetString("LeaveAcomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;META HTTP-EQUIV=&quot;Content-Type&quot; CONTENT=&quot;text/html;charset=Unicode&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;
        ///Notification about new comment on blogpost &lt;b&gt;&lt;a href=&quot;{3}&quot;&gt;{0}&lt;/a&gt;&lt;/b&gt;&lt;/p&gt;
        ///&lt;/p&gt;
        ///&lt;hr/&gt;
        ///&lt;h2&gt;Comment body (by {4}):&lt;/h2&gt;
        ///&lt;p&gt;
        ///{1}
        ///&lt;/p&gt;
        ///&lt;hr/&gt;
        ///&lt;p&gt;
        ///For unsubscribe please use current link &lt;a href=&quot;{2}&quot;&gt;{2}&lt;/a&gt;.
        ///&lt;/p&gt;{5}
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string NotificationBody {
            get {
                return ResourceManager.GetString("NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to get notifications about new comments at this topic, please fill email text box and check proper item. If you want to place source code in comment body place it in tags &lt;b&gt;[code]...[/code]&lt;/b&gt;, you can set language like this [code cs]...[/code], where cs can be cs, html, xml, java, js, php, sql, cpp, css..
        /// </summary>
        internal static string NotificationInformation {
            get {
                return ResourceManager.GetString("NotificationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New comment on blogpost - .
        /// </summary>
        internal static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Other Accounts.
        /// </summary>
        internal static string OtherContacts {
            get {
                return ResourceManager.GetString("OtherContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more....
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more... (redirect to http://outcoldman.ru).
        /// </summary>
        internal static string ReadMoreRss {
            get {
                return ResourceManager.GetString("ReadMoreRss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Tag.
        /// </summary>
        internal static string SelectedTag {
            get {
                return ResourceManager.GetString("SelectedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me about new comments.
        /// </summary>
        internal static string SendNotifications {
            get {
                return ResourceManager.GetString("SendNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отписаться.
        /// </summary>
        internal static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to unsubscribe?.
        /// </summary>
        internal static string UnsubscribeQuestion {
            get {
                return ResourceManager.GetString("UnsubscribeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        internal static string UnsubscribeTitle {
            get {
                return ResourceManager.GetString("UnsubscribeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website url.
        /// </summary>
        internal static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Email address (Use it if want to talk to me like a Microsoft employee about VS Profiler, etc).
        /// </summary>
        internal static string WorkEmailAddress {
            get {
                return ResourceManager.GetString("WorkEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You might also like.
        /// </summary>
        internal static string YouMightAlsoLike {
            get {
                return ResourceManager.GetString("YouMightAlsoLike", resourceCulture);
            }
        }
    }
}
