//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LocalDatabaseModel", "FK_Comment_BlogPost", "BlogPost", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PersonalWeb.Model.BlogPost), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PersonalWeb.Model.Comment), true)]
[assembly: EdmRelationshipAttribute("LocalDatabaseModel", "FK_CommentSubscription_BlogPost", "BlogPost", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PersonalWeb.Model.BlogPost), "CommentSubscription", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PersonalWeb.Model.CommentSubscription), true)]
[assembly: EdmRelationshipAttribute("LocalDatabaseModel", "FK_Notifications_Comment", "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PersonalWeb.Model.Comment), "Notification", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PersonalWeb.Model.Notification), true)]
[assembly: EdmRelationshipAttribute("LocalDatabaseModel", "BlogPostTag", "BlogPost", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PersonalWeb.Model.BlogPost), "Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PersonalWeb.Model.Tag))]

#endregion

namespace PersonalWeb.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LocalDatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LocalDatabaseEntities object using the connection string found in the 'LocalDatabaseEntities' section of the application configuration file.
        /// </summary>
        public LocalDatabaseEntities() : base("name=LocalDatabaseEntities", "LocalDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LocalDatabaseEntities object.
        /// </summary>
        public LocalDatabaseEntities(string connectionString) : base(connectionString, "LocalDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LocalDatabaseEntities object.
        /// </summary>
        public LocalDatabaseEntities(EntityConnection connection) : base(connection, "LocalDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlogPost> BlogPosts
        {
            get
            {
                if ((_BlogPosts == null))
                {
                    _BlogPosts = base.CreateObjectSet<BlogPost>("BlogPosts");
                }
                return _BlogPosts;
            }
        }
        private ObjectSet<BlogPost> _BlogPosts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comment> Comments
        {
            get
            {
                if ((_Comments == null))
                {
                    _Comments = base.CreateObjectSet<Comment>("Comments");
                }
                return _Comments;
            }
        }
        private ObjectSet<Comment> _Comments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CommentSubscription> CommentSubscriptions
        {
            get
            {
                if ((_CommentSubscriptions == null))
                {
                    _CommentSubscriptions = base.CreateObjectSet<CommentSubscription>("CommentSubscriptions");
                }
                return _CommentSubscriptions;
            }
        }
        private ObjectSet<CommentSubscription> _CommentSubscriptions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Notification> Notifications
        {
            get
            {
                if ((_Notifications == null))
                {
                    _Notifications = base.CreateObjectSet<Notification>("Notifications");
                }
                return _Notifications;
            }
        }
        private ObjectSet<Notification> _Notifications;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tag> Tags
        {
            get
            {
                if ((_Tags == null))
                {
                    _Tags = base.CreateObjectSet<Tag>("Tags");
                }
                return _Tags;
            }
        }
        private ObjectSet<Tag> _Tags;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlogPosts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlogPosts(BlogPost blogPost)
        {
            base.AddObject("BlogPosts", blogPost);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComments(Comment comment)
        {
            base.AddObject("Comments", comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CommentSubscriptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommentSubscriptions(CommentSubscription commentSubscription)
        {
            base.AddObject("CommentSubscriptions", commentSubscription);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Notifications EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNotifications(Notification notification)
        {
            base.AddObject("Notifications", notification);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTags(Tag tag)
        {
            base.AddObject("Tags", tag);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LocalDatabaseModel", Name="BlogPost")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlogPost : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlogPost object.
        /// </summary>
        /// <param name="postID">Initial value of the PostID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="language">Initial value of the Language property.</param>
        /// <param name="htmlText">Initial value of the HtmlText property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="isPublic">Initial value of the IsPublic property.</param>
        /// <param name="htmlAbstraction">Initial value of the HtmlAbstraction property.</param>
        /// <param name="isJustAbstraction">Initial value of the IsJustAbstraction property.</param>
        /// <param name="isForExternal">Initial value of the IsForExternal property.</param>
        public static BlogPost CreateBlogPost(global::System.Int32 postID, global::System.String title, global::System.String language, global::System.String htmlText, global::System.DateTime date, global::System.Boolean isPublic, global::System.String htmlAbstraction, global::System.Boolean isJustAbstraction, global::System.Boolean isForExternal)
        {
            BlogPost blogPost = new BlogPost();
            blogPost.PostID = postID;
            blogPost.Title = title;
            blogPost.Language = language;
            blogPost.HtmlText = htmlText;
            blogPost.Date = date;
            blogPost.IsPublic = isPublic;
            blogPost.HtmlAbstraction = htmlAbstraction;
            blogPost.IsJustAbstraction = isJustAbstraction;
            blogPost.IsForExternal = isForExternal;
            return blogPost;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PostID
        {
            get
            {
                return _PostID;
            }
            set
            {
                if (_PostID != value)
                {
                    OnPostIDChanging(value);
                    ReportPropertyChanging("PostID");
                    _PostID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostID");
                    OnPostIDChanged();
                }
            }
        }
        private global::System.Int32 _PostID;
        partial void OnPostIDChanging(global::System.Int32 value);
        partial void OnPostIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Language
        {
            get
            {
                return _Language;
            }
            set
            {
                OnLanguageChanging(value);
                ReportPropertyChanging("Language");
                _Language = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Language");
                OnLanguageChanged();
            }
        }
        private global::System.String _Language;
        partial void OnLanguageChanging(global::System.String value);
        partial void OnLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HtmlText
        {
            get
            {
                return _HtmlText;
            }
            set
            {
                OnHtmlTextChanging(value);
                ReportPropertyChanging("HtmlText");
                _HtmlText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HtmlText");
                OnHtmlTextChanged();
            }
        }
        private global::System.String _HtmlText;
        partial void OnHtmlTextChanging(global::System.String value);
        partial void OnHtmlTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPublic
        {
            get
            {
                return _IsPublic;
            }
            set
            {
                OnIsPublicChanging(value);
                ReportPropertyChanging("IsPublic");
                _IsPublic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPublic");
                OnIsPublicChanged();
            }
        }
        private global::System.Boolean _IsPublic;
        partial void OnIsPublicChanging(global::System.Boolean value);
        partial void OnIsPublicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] DateChanged
        {
            get
            {
                return StructuralObject.GetValidValue(_DateChanged);
            }
            set
            {
                OnDateChangedChanging(value);
                ReportPropertyChanging("DateChanged");
                _DateChanged = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DateChanged");
                OnDateChangedChanged();
            }
        }
        private global::System.Byte[] _DateChanged;
        partial void OnDateChangedChanging(global::System.Byte[] value);
        partial void OnDateChangedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HtmlAbstraction
        {
            get
            {
                return _HtmlAbstraction;
            }
            set
            {
                OnHtmlAbstractionChanging(value);
                ReportPropertyChanging("HtmlAbstraction");
                _HtmlAbstraction = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HtmlAbstraction");
                OnHtmlAbstractionChanged();
            }
        }
        private global::System.String _HtmlAbstraction;
        partial void OnHtmlAbstractionChanging(global::System.String value);
        partial void OnHtmlAbstractionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsJustAbstraction
        {
            get
            {
                return _IsJustAbstraction;
            }
            set
            {
                OnIsJustAbstractionChanging(value);
                ReportPropertyChanging("IsJustAbstraction");
                _IsJustAbstraction = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsJustAbstraction");
                OnIsJustAbstractionChanged();
            }
        }
        private global::System.Boolean _IsJustAbstraction;
        partial void OnIsJustAbstractionChanging(global::System.Boolean value);
        partial void OnIsJustAbstractionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsForExternal
        {
            get
            {
                return _IsForExternal;
            }
            set
            {
                OnIsForExternalChanging(value);
                ReportPropertyChanging("IsForExternal");
                _IsForExternal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsForExternal");
                OnIsForExternalChanged();
            }
        }
        private global::System.Boolean _IsForExternal;
        partial void OnIsForExternalChanging(global::System.Boolean value);
        partial void OnIsForExternalChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LocalDatabaseModel", "FK_Comment_BlogPost", "Comment")]
        public EntityCollection<Comment> Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("LocalDatabaseModel.FK_Comment_BlogPost", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("LocalDatabaseModel.FK_Comment_BlogPost", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LocalDatabaseModel", "FK_CommentSubscription_BlogPost", "CommentSubscription")]
        public EntityCollection<CommentSubscription> CommentSubscriptions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CommentSubscription>("LocalDatabaseModel.FK_CommentSubscription_BlogPost", "CommentSubscription");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CommentSubscription>("LocalDatabaseModel.FK_CommentSubscription_BlogPost", "CommentSubscription", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LocalDatabaseModel", "BlogPostTag", "Tag")]
        public EntityCollection<Tag> Tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tag>("LocalDatabaseModel.BlogPostTag", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tag>("LocalDatabaseModel.BlogPostTag", "Tag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LocalDatabaseModel", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="commentID">Initial value of the CommentID property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="postID">Initial value of the PostID property.</param>
        /// <param name="userIP">Initial value of the UserIP property.</param>
        /// <param name="isSpam">Initial value of the IsSpam property.</param>
        public static Comment CreateComment(global::System.Int32 commentID, global::System.String body, global::System.DateTime date, global::System.Int32 postID, global::System.String userIP, global::System.Boolean isSpam)
        {
            Comment comment = new Comment();
            comment.CommentID = commentID;
            comment.Body = body;
            comment.Date = date;
            comment.PostID = postID;
            comment.UserIP = userIP;
            comment.IsSpam = isSpam;
            return comment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommentID
        {
            get
            {
                return _CommentID;
            }
            set
            {
                if (_CommentID != value)
                {
                    OnCommentIDChanging(value);
                    ReportPropertyChanging("CommentID");
                    _CommentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CommentID");
                    OnCommentIDChanged();
                }
            }
        }
        private global::System.Int32 _CommentID;
        partial void OnCommentIDChanging(global::System.Int32 value);
        partial void OnCommentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PostID
        {
            get
            {
                return _PostID;
            }
            set
            {
                OnPostIDChanging(value);
                ReportPropertyChanging("PostID");
                _PostID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostID");
                OnPostIDChanged();
            }
        }
        private global::System.Int32 _PostID;
        partial void OnPostIDChanging(global::System.Int32 value);
        partial void OnPostIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserIP
        {
            get
            {
                return _UserIP;
            }
            set
            {
                OnUserIPChanging(value);
                ReportPropertyChanging("UserIP");
                _UserIP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserIP");
                OnUserIPChanged();
            }
        }
        private global::System.String _UserIP;
        partial void OnUserIPChanging(global::System.String value);
        partial void OnUserIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserEmail
        {
            get
            {
                return _UserEmail;
            }
            set
            {
                OnUserEmailChanging(value);
                ReportPropertyChanging("UserEmail");
                _UserEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserEmail");
                OnUserEmailChanged();
            }
        }
        private global::System.String _UserEmail;
        partial void OnUserEmailChanging(global::System.String value);
        partial void OnUserEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserWeb
        {
            get
            {
                return _UserWeb;
            }
            set
            {
                OnUserWebChanging(value);
                ReportPropertyChanging("UserWeb");
                _UserWeb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserWeb");
                OnUserWebChanged();
            }
        }
        private global::System.String _UserWeb;
        partial void OnUserWebChanging(global::System.String value);
        partial void OnUserWebChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserAgent
        {
            get
            {
                return _UserAgent;
            }
            set
            {
                OnUserAgentChanging(value);
                ReportPropertyChanging("UserAgent");
                _UserAgent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserAgent");
                OnUserAgentChanged();
            }
        }
        private global::System.String _UserAgent;
        partial void OnUserAgentChanging(global::System.String value);
        partial void OnUserAgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSpam
        {
            get
            {
                return _IsSpam;
            }
            set
            {
                OnIsSpamChanging(value);
                ReportPropertyChanging("IsSpam");
                _IsSpam = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSpam");
                OnIsSpamChanged();
            }
        }
        private global::System.Boolean _IsSpam;
        partial void OnIsSpamChanging(global::System.Boolean value);
        partial void OnIsSpamChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LocalDatabaseModel", "FK_Comment_BlogPost", "BlogPost")]
        public BlogPost BlogPost
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BlogPost>("LocalDatabaseModel.FK_Comment_BlogPost", "BlogPost").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BlogPost>("LocalDatabaseModel.FK_Comment_BlogPost", "BlogPost").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BlogPost> BlogPostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BlogPost>("LocalDatabaseModel.FK_Comment_BlogPost", "BlogPost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BlogPost>("LocalDatabaseModel.FK_Comment_BlogPost", "BlogPost", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LocalDatabaseModel", "FK_Notifications_Comment", "Notification")]
        public EntityCollection<Notification> Notifications
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Notification>("LocalDatabaseModel.FK_Notifications_Comment", "Notification");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Notification>("LocalDatabaseModel.FK_Notifications_Comment", "Notification", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LocalDatabaseModel", Name="CommentSubscription")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CommentSubscription : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CommentSubscription object.
        /// </summary>
        /// <param name="postID">Initial value of the PostID property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="subscriptionID">Initial value of the SubscriptionID property.</param>
        public static CommentSubscription CreateCommentSubscription(global::System.Int32 postID, global::System.String email, global::System.Guid subscriptionID)
        {
            CommentSubscription commentSubscription = new CommentSubscription();
            commentSubscription.PostID = postID;
            commentSubscription.Email = email;
            commentSubscription.SubscriptionID = subscriptionID;
            return commentSubscription;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PostID
        {
            get
            {
                return _PostID;
            }
            set
            {
                OnPostIDChanging(value);
                ReportPropertyChanging("PostID");
                _PostID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostID");
                OnPostIDChanged();
            }
        }
        private global::System.Int32 _PostID;
        partial void OnPostIDChanging(global::System.Int32 value);
        partial void OnPostIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid SubscriptionID
        {
            get
            {
                return _SubscriptionID;
            }
            set
            {
                if (_SubscriptionID != value)
                {
                    OnSubscriptionIDChanging(value);
                    ReportPropertyChanging("SubscriptionID");
                    _SubscriptionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubscriptionID");
                    OnSubscriptionIDChanged();
                }
            }
        }
        private global::System.Guid _SubscriptionID;
        partial void OnSubscriptionIDChanging(global::System.Guid value);
        partial void OnSubscriptionIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LocalDatabaseModel", "FK_CommentSubscription_BlogPost", "BlogPost")]
        public BlogPost BlogPost
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BlogPost>("LocalDatabaseModel.FK_CommentSubscription_BlogPost", "BlogPost").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BlogPost>("LocalDatabaseModel.FK_CommentSubscription_BlogPost", "BlogPost").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BlogPost> BlogPostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BlogPost>("LocalDatabaseModel.FK_CommentSubscription_BlogPost", "BlogPost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BlogPost>("LocalDatabaseModel.FK_CommentSubscription_BlogPost", "BlogPost", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LocalDatabaseModel", Name="Notification")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Notification : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Notification object.
        /// </summary>
        /// <param name="notificationID">Initial value of the NotificationID property.</param>
        /// <param name="commentID">Initial value of the CommentID property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="isSent">Initial value of the IsSent property.</param>
        public static Notification CreateNotification(global::System.Int32 notificationID, global::System.Int32 commentID, global::System.String email, global::System.Boolean isSent)
        {
            Notification notification = new Notification();
            notification.NotificationID = notificationID;
            notification.CommentID = commentID;
            notification.Email = email;
            notification.IsSent = isSent;
            return notification;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NotificationID
        {
            get
            {
                return _NotificationID;
            }
            set
            {
                if (_NotificationID != value)
                {
                    OnNotificationIDChanging(value);
                    ReportPropertyChanging("NotificationID");
                    _NotificationID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NotificationID");
                    OnNotificationIDChanged();
                }
            }
        }
        private global::System.Int32 _NotificationID;
        partial void OnNotificationIDChanging(global::System.Int32 value);
        partial void OnNotificationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommentID
        {
            get
            {
                return _CommentID;
            }
            set
            {
                OnCommentIDChanging(value);
                ReportPropertyChanging("CommentID");
                _CommentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommentID");
                OnCommentIDChanged();
            }
        }
        private global::System.Int32 _CommentID;
        partial void OnCommentIDChanging(global::System.Int32 value);
        partial void OnCommentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSent
        {
            get
            {
                return _IsSent;
            }
            set
            {
                OnIsSentChanging(value);
                ReportPropertyChanging("IsSent");
                _IsSent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSent");
                OnIsSentChanged();
            }
        }
        private global::System.Boolean _IsSent;
        partial void OnIsSentChanging(global::System.Boolean value);
        partial void OnIsSentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LocalDatabaseModel", "FK_Notifications_Comment", "Comment")]
        public Comment Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comment>("LocalDatabaseModel.FK_Notifications_Comment", "Comment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comment>("LocalDatabaseModel.FK_Notifications_Comment", "Comment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Comment> CommentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comment>("LocalDatabaseModel.FK_Notifications_Comment", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Comment>("LocalDatabaseModel.FK_Notifications_Comment", "Comment", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LocalDatabaseModel", Name="Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="tagID">Initial value of the TagID property.</param>
        public static Tag CreateTag(global::System.Int32 tagID)
        {
            Tag tag = new Tag();
            tag.TagID = tagID;
            return tag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TagID
        {
            get
            {
                return _TagID;
            }
            set
            {
                if (_TagID != value)
                {
                    OnTagIDChanging(value);
                    ReportPropertyChanging("TagID");
                    _TagID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TagID");
                    OnTagIDChanged();
                }
            }
        }
        private global::System.Int32 _TagID;
        partial void OnTagIDChanging(global::System.Int32 value);
        partial void OnTagIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LocalDatabaseModel", "BlogPostTag", "BlogPost")]
        public EntityCollection<BlogPost> BlogPosts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlogPost>("LocalDatabaseModel.BlogPostTag", "BlogPost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlogPost>("LocalDatabaseModel.BlogPostTag", "BlogPost", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
