//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalWeb.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceRu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalWeb.Web.Resources.ResourceRu", typeof(ResourceRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обо Мне / CV.
        /// </summary>
        internal static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить комментарий.
        /// </summary>
        internal static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аноним.
        /// </summary>
        internal static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блог.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст комментария* (возможно использовать html).
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобильный телефон.
        /// </summary>
        internal static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете использовать эту страницу для подсветки исходного кода (Based on Code Snippet plugin for Windows Live Writer)..
        /// </summary>
        internal static string CodeHighlighterInfo {
            get {
                return ResourceManager.GetString("CodeHighlighterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подсветка синтаксиса.
        /// </summary>
        internal static string CodeHighlighterTitle {
            get {
                return ResourceManager.GetString("CodeHighlighterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий успешно добавлен. .
        /// </summary>
        internal static string CommentAdded {
            get {
                return ResourceManager.GetString("CommentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий успешно добавлен, но помечен как спам..
        /// </summary>
        internal static string CommentAddedAsSpam {
            get {
                return ResourceManager.GetString("CommentAddedAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неудалось добавить комментарий. Убедитесь, что вы не используете Javascript в тексте комментария. Если произошла ошибка на сайте, пожалуйста, свяжитесь со мной..
        /// </summary>
        internal static string CommentNotAdded {
            get {
                return ResourceManager.GetString("CommentNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможность использовать XDT трансформацию, которая появилась в ASP.NET 4 для любых файлов..
        /// </summary>
        internal static string ConfigTransformationTool {
            get {
                return ResourceManager.GetString("ConfigTransformationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размещенная на сайте информация является моим личным мнением..
        /// </summary>
        internal static string ContentOfSite {
            get {
                return ResourceManager.GetString("ContentOfSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неудалось добавить комментарий.
        /// </summary>
        internal static string CouldntAddComment {
            get {
                return ResourceManager.GetString("CouldntAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно выполнить данное действие.
        /// </summary>
        internal static string CouldntExecute {
            get {
                return ResourceManager.GetString("CouldntExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неудалось обработать запрос.
        /// </summary>
        internal static string CouldntShowPreview {
            get {
                return ResourceManager.GetString("CouldntShowPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У нас уже есть такой комментарий в базе данных. Похоже, что вы пытаетесь добавить свой комментарий второй раз. Обновите страницу через пару минут, и вы увидите свой комментарий (если он не был помечен как спам)..
        /// </summary>
        internal static string DublicateComment {
            get {
                return ResourceManager.GetString("DublicateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email (не будет опубликован).
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Адрес.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнить.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните поле &quot;Текст комментария&quot;..
        /// </summary>
        internal static string FillBodyComment {
            get {
                return ResourceManager.GetString("FillBodyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните поле &quot;Email&quot;, либо отключите подписку на новые комментарии..
        /// </summary>
        internal static string FillEmailComment {
            get {
                return ResourceManager.GetString("FillEmailComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для прочтения остальных записей перейдите на страницу {0}....
        /// </summary>
        internal static string FindMore {
            get {
                return ResourceManager.GetString("FindMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Code (Example):.
        /// </summary>
        internal static string FormattedCodeExample {
            get {
                return ResourceManager.GetString("FormattedCodeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Code (Html):.
        /// </summary>
        internal static string FormattedCodeHtml {
            get {
                return ResourceManager.GetString("FormattedCodeHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домашняя.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверяемый текст.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст комментария.
        /// </summary>
        internal static string InputComment {
            get {
                return ResourceManager.GetString("InputComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите email адрес.
        /// </summary>
        internal static string InputEmail {
            get {
                return ResourceManager.GetString("InputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя.
        /// </summary>
        internal static string InputName {
            get {
                return ResourceManager.GetString("InputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите web адрес.
        /// </summary>
        internal static string InputWeb {
            get {
                return ResourceManager.GetString("InputWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение даст возможноть использовать горячие клавиши Win + (Left | Right | Up | Bottom) в Windows XP и Vista.
        /// </summary>
        internal static string KeysExtenderInfo {
            get {
                return ResourceManager.GetString("KeysExtenderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Keys Extender.
        /// </summary>
        internal static string KeysExtenderTitle {
            get {
                return ResourceManager.GetString("KeysExtenderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментировать.
        /// </summary>
        internal static string LeaveAcomment {
            get {
                return ResourceManager.GetString("LeaveAcomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Местоположение.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Совпадение {0} (Индекс {1}) - &apos;{2}&apos; &lt;br/&gt;.
        /// </summary>
        internal static string MatchResult {
            get {
                return ResourceManager.GetString("MatchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;META HTTP-EQUIV=&quot;Content-Type&quot; CONTENT=&quot;text/html;charset=Unicode&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;
        ///Автоматическое уведомления о новом комментарии к топику &lt;b&gt;&lt;a href=&quot;{3}&quot;&gt;{0}&lt;/a&gt;&lt;/b&gt;&lt;/p&gt;
        ///&lt;/p&gt;
        ///&lt;hr/&gt;
        ///&lt;h2&gt;Текст комментария (by {4}):&lt;/h2&gt;
        ///&lt;p&gt;
        ///{1}
        ///&lt;/p&gt;
        ///&lt;hr/&gt;
        ///&lt;p&gt;
        ///Если вы хотите отписаться от получения извещений о новых комментариях к данному топику - перейдите по ссылке &lt;a href=&quot;{2}&quot;&gt;{2}&lt;/a&gt;.
        ///&lt;/p&gt;{5}
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string NotificationBody {
            get {
                return ResourceManager.GetString("NotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы хотите получать уведомления о новых комментариях к данному топику, укажите, пожалуйста, email и отметьте соответствующий пункт в форме. Если вы хотите добавить код в тексте комментария, то заключите его внутри тега &lt;b&gt;[code]...[/code]&lt;/b&gt;, более того можно уточнить язык, на котором написан данный код при помощи [code cs]...[/code], где вместо cs могут быть cs, html, xml, java, js, php, sql, cpp, css..
        /// </summary>
        internal static string NotificationInformation {
            get {
                return ResourceManager.GetString("NotificationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый комментарий к топику - .
        /// </summary>
        internal static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие контакты.
        /// </summary>
        internal static string OtherContacts {
            get {
                return ResourceManager.GetString("OtherContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предпросмотр.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читать дальше....
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читать дальше... (redirect to http://outcoldman.ru).
        /// </summary>
        internal static string ReadMoreRss {
            get {
                return ResourceManager.GetString("ReadMoreRss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регулярное выражение.
        /// </summary>
        internal static string RegEx {
            get {
                return ResourceManager.GetString("RegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете использовать эту страницу для тестирования регулярных выражений.
        /// </summary>
        internal static string RegExInfo {
            get {
                return ResourceManager.GetString("RegExInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регулярные выражения.
        /// </summary>
        internal static string RegExTitle {
            get {
                return ResourceManager.GetString("RegExTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный тег.
        /// </summary>
        internal static string SelectedTag {
            get {
                return ResourceManager.GetString("SelectedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомлять о новых комментариях.
        /// </summary>
        internal static string SendNotifications {
            get {
                return ResourceManager.GetString("SendNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете использовать эту страницу для того чтобы узнать свой IP адрес.
        /// </summary>
        internal static string ShowIPInfo {
            get {
                return ResourceManager.GetString("ShowIPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать IP адрес.
        /// </summary>
        internal static string ShowIPTitle {
            get {
                return ResourceManager.GetString("ShowIPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code:.
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string SourceCodeType {
            get {
                return ResourceManager.GetString("SourceCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложения.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение для подсчета статистики по используемым хеш-тегам, словам и пользователям в ваших твиттах.
        /// </summary>
        internal static string TwitterStatisticInfo {
            get {
                return ResourceManager.GetString("TwitterStatisticInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Cloud.
        /// </summary>
        internal static string TwitterStatisticTitle {
            get {
                return ResourceManager.GetString("TwitterStatisticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отписаться.
        /// </summary>
        internal static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотите отписаться от получения новых комментариев к данному топику?.
        /// </summary>
        internal static string UnsubscribeQuestion {
            get {
                return ResourceManager.GetString("UnsubscribeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отписаться от получения уведомлений о новых комментариях.
        /// </summary>
        internal static string UnsubscribeTitle {
            get {
                return ResourceManager.GetString("UnsubscribeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт.
        /// </summary>
        internal static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочий Email адрес (Используйте его, если вы хотите поговорить со мной, как с работником Microsoft, о тулах над которыми я работаю):.
        /// </summary>
        internal static string WorkEmailAddress {
            get {
                return ResourceManager.GetString("WorkEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вас также может заинтересовать.
        /// </summary>
        internal static string YouMightAlsoLike {
            get {
                return ResourceManager.GetString("YouMightAlsoLike", resourceCulture);
            }
        }
    }
}
